# monitoring/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'currency-api'
    static_configs:
      - targets: ['host.docker.internal:8080']  # ← ИЗМЕНИТЕ НА ЭТО!
        labels:
          service: 'currency-prediction-api'
          environment: 'lab11'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']