apiVersion: v1
kind: Service
metadata:
  name: currency-api-service
  labels:
    app: currency-api
spec:
  type: NodePort
  selector:
    app: currency-api
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
---
# Для доступа внутри кластера
apiVersion: v1
kind: Service
metadata:
  name: currency-api-cluster
spec:
  type: ClusterIP
  selector:
    app: currency-api
  ports:
  - port: 8080
    targetPort: 8080